version: '3.8'
services:
  rotulusdb:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=beluomini
      - POSTGRES_PASSWORD=minipass
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DATABASE_USER} -d ${DATABASE_URL}']
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      rotulusdb:
        condition: service_healthy
    env_file:
      - ./backend/.env.development.local
    ports:
      - '${PORT}:${PORT}'
    environment:
      - PORT = ${PORT}
      - DATABASE_URL = ${DATABASE_URL}
      - JWT_SECRET = ${JWT_SECRET}
    volumes:
      - .:/usr/src/api
      - /usr/src/api/node_modules
volumes:
  postgres: