import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    all: {
        flex: 1,
        backgroundColor: '#fff',
    },
    container: {
        flex: 1,
        backgroundColor: '#D33333',
        alignItems: 'center',
        paddingTop: "20%",
    },
    header: {
        width: '100%',
        alignItems: 'center',
        marginBottom: "10%",
    },
    alergies: {
        width: '100%',
        backgroundColor: '#fff',
        alignItems: 'center',
    },
    arrowIconButton: {
        position: 'absolute',
        left: "7%",
        top: "1%",
    },
    arrowIcon: {
        width: 30,
        height: 30,
        transform: [{ rotate: '90deg' }],
    },
    title: {
        fontFamily: 'Roboto',
        fontSize: 25,
        color: '#fff',
        marginBottom: "15%",
    },
    userIcon: {
        width: 100,
        height: 100,
        marginBottom: 10,
    },
    userName: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: "10%",
        marginBottom: "7%",
    },
    userNameText: {
        fontFamily: 'Roboto',
        fontSize: 20,
        color: '#fff',
    },
    userNameInput: {
        fontFamily: 'Roboto',
        fontSize: 20,
        color: '#fff',
        borderBottomWidth: 1,
        borderBottomColor: '#fff',
    },
    editIconButton: {
        marginLeft: 10,
    },
    editIcon: {
        width: 20,
        height: 20,
    },
    okIcon: {
        width: 20,
        height: 20,
    },
    email: {
        fontFamily: 'Roboto',
        fontSize: 20,
        color: '#fff',
    },
    alergiesTitle: {
        fontFamily: 'Roboto',
        fontSize: 20,
        color: '#000',
        marginTop: "5%",
    },
    noAlergies: {
        width: '80%',
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#eee',
        marginTop: "5%",
    },
    noAlergiesText: {
        textAlign: 'center',
        fontFamily: 'Roboto',
        fontSize: 15,
        color: '#000',
    },
    alergiesBoxesSelected: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'flex-start',
        alignItems: 'center',
        width: '80%',
        marginTop: "5%",
    },
    alergiesBoxSelected: {
        flexDirection: 'row',
        height: 30,
        width: "28%",
        backgroundColor: '#D33333',
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: "5%",
        marginRight: "5%",
        paddingHorizontal: "4%",
    },
    alergiesBoxSelectedText: {
        fontFamily: 'Roboto',
        fontSize: 16,
        color: '#fff',
    },
    alergiesSearchLabel: {
        flexDirection: 'row',
        width: '80%',
        height: 40,
        backgroundColor: '#fff',
        borderRadius: 10,
        borderWidth: 1,
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 15,
        marginTop: "5%",
    },
    alergiesBox: {
        flex: 1,
        maxHeight: 150,
        width: '80%',
        flexDirection: 'column',
        backgroundColor: '#eee',
        marginBottom: 10,
        borderBottomRightRadius: 10,
        borderBottomLeftRadius: 10,
    },
    alergiesBoxItem: {
        width: '100%',
        height: 40,
        borderBottomWidth: 1,
        borderBottomEndRadius: 10,
        borderBottomLeftRadius: 10,
        borderBottomColor: '#ccc',
        alignItems: 'center',
        justifyContent: 'center',
    },
    alergiesBoxItemText: {
        fontFamily: 'Roboto',
        fontSize: 16,
        color: '#000',
    },
    alergiesButtons: {
        flex: 1,
        width: '80%',
        alignItems: 'center',
        marginTop: "10%",
    },
    buttonSave: {
        height: 40,
        backgroundColor: '#D33333',
        paddingHorizontal: 20,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    buttonSaveText: {
        fontFamily: 'Roboto',
        fontSize: 16,
        color: '#fff',
    },
    buttonSaved: {
        height: 40,
        backgroundColor: '#ccc',
        paddingHorizontal: 20,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    buttonSavedText: {
        fontFamily: 'Roboto',
        fontSize: 16,
        color: '#fff',
    },
  });

export default styles;